"""empty message

Revision ID: e9d14da1e18d
Revises: 
Create Date: 2022-05-06 11:52:20.299142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d14da1e18d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h_schools',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.String(length=64), nullable=False),
    sa.Column('_region', sa.String(length=20), nullable=False),
    sa.Column('_street', sa.String(length=64), nullable=False),
    sa.Column('_number', sa.String(length=3), nullable=False),
    sa.Column('_phone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('r_school', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['r_school'], ['h_schools._id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('max_student', sa.Integer(), nullable=False),
    sa.Column('min_student', sa.Integer(), nullable=False),
    sa.Column('n_hour', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.DATE(), nullable=False),
    sa.Column('end_month', sa.DATE(), nullable=False),
    sa.Column('professor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=True)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.TIME(), nullable=False),
    sa.Column('end_hour', sa.TIME(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=2083), nullable=False),
    sa.Column('structure', sa.String(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_corse',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_corse')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('h_schools')
    # ### end Alembic commands ###
